# Generated by Django 5.1.4 on 2024-12-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dis_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='名称'),
        ),
    ]
