# Generated by Django 5.1.4 on 2024-12-12 04:53

import vio.utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio', '0004_alter_profile_dis_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=vio.utils.file_utils.upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
