# Generated by Django 5.1.4 on 2024-12-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio', '0006_datafile_author_datafile_original_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('adcode', models.CharField(max_length=10)),
                ('weather', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=5)),
                ('winddirection', models.CharField(max_length=10)),
                ('windpower', models.CharField(max_length=5)),
                ('humidity', models.CharField(max_length=5)),
                ('reporttime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
