# Generated by Django 5.1.4 on 2024-12-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio', '0009_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
