# Generated by Django 5.1.4 on 2024-12-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio', '0011_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='vio.tag'),
        ),
    ]
