# Generated by Django 5.1.4 on 2024-12-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vio', '0013_datafile_row_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='row_count',
        ),
    ]
